DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;

USE employee_db;


CREATE TABLE deptT (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL
);

CREATE TABLE roleT (
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL, 
department_id INT,
FOREIGN KEY(department_id)
REFERENCES deptT(id)
);

CREATE TABLE emT (
id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL, 
last_name VARCHAR(30) NOT NULL, 
role_id INT NOT NULL,
manager_id INT,
FOREIGN KEY (role_id)
REFERENCES roleT(id),

FOREIGN KEY (manager_id)
REFERENCES emT(id)
);